export const CONTRACT_ABI = [
  "function verifyStaff(string hospitalName, string post, string idNumber, bytes32 passwordHash) returns (bool)",
  "function logDataAccess(string idNumber, string hospitalName, string post, string dataType)",
  "function logSuspiciousActivity(string idNumber, string activityType)",
  "function registerStaff(string hospitalName, string post, string idNumber, bytes32 passwordHash)",
  "function preRegisterStaff(string fullName, string idNumber, string post, string hospitalName, string department, bytes32 emailHash)",
  "function checkPreRegistered(string idNumber) view returns (bool exists, bool activated)",
  "function getPreRegisteredDetails(string idNumber) view returns (string fullName, string post, string hospitalName, string department)",
  "function activateStaff(string idNumber, bytes32 passwordHash)",
  "function storePublicKey(string idNumber, string publicKey)",
  "function getPublicKey(string idNumber) view returns (string)",
  "function logRecordSignature(string idNumber, string recordHash, bool valid)",
  "function staffExists(string idNumber) view returns (bool)",
  "event LoginAttempt(string idNumber, string hospitalName, bool success, uint256 timestamp)",
  "event DataAccessed(string idNumber, string hospitalName, string post, string dataType, uint256 timestamp)",
  "event SuspiciousActivity(string idNumber, string activityType, uint256 timestamp)",
  "event StaffPreRegistered(string idNumber, string post, uint256 timestamp)",
  "event StaffActivated(string idNumber, uint256 timestamp)",
  "event PublicKeyStored(string idNumber, uint256 timestamp)",
  "event RecordSignatureVerified(string idNumber, string recordHash, bool valid, uint256 timestamp)",
];
